'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'../src');
const files=['settings.js','management.js','app.js'].map(name=>fs.readFileSync(path.join(root,name),'utf8'));
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
let count=0;
function setup(){
  const els=new Map(),listeners={},requests=[];
  function el(key){
    if(!els.has(key))els.set(key,{innerHTML:'',textContent:'',value:'',hidden:false,disabled:false,dataset:{},open:false,
      classList:{toggle(){},add(){},remove(){}},addEventListener(){},querySelectorAll(){return [];},setAttribute(){},
      showModal(){this.open=true;},close(){this.open=false;},reset(){},focus(){},setSelectionRange(){}});
    return els.get(key);
  }
  const document={querySelector:el,querySelectorAll:()=>[],getElementById:id=>el('#'+id),activeElement:null,documentElement:{dataset:{theme:'dark'}},
    addEventListener(type,fn){(listeners[type]??=[]).push(fn);}};
  const context=vm.createContext({console,Date,Map,Set,document,localStorage:{getItem(){return null;},setItem(){}},
    window:{addEventListener(){}},location:{hash:''},history:{replaceState(a,b,hash){context.location.hash=hash;}},
    setTimeout(){return 1;},clearTimeout(){},FormData:class{constructor(form){this.form=form;}*[Symbol.iterator](){yield*Object.entries(this.form.values||{});}},
    fetch:async(url,options)=>{requests.push({url,options});return handler(url,options);}});
  const run=code=>vm.runInContext(code,context);
  let handler=async()=>({ok:true,status:200,json:async()=>run('data')});
  vm.runInContext(files[0],context);vm.runInContext(files[1],context);
  vm.runInContext(files[2].slice(0,files[2].lastIndexOf('fillIcons();try')),context);
  run(`data={revision:4,projects:[{id:'p1',name:'开发项目',description:'说明',color:'blue'},{id:'p2',name:'另一个项目',description:'',color:'green'}],activities:[],tasks:[],requirements:[],defects:[]};loaded=true;ready=true;section='tasks';`);
  const emit=async(type,target)=>{if(type==='submit'&&target.id==='management-form'){Object.assign(el('#management-form'),target);target=el('#management-form');}for(const fn of listeners[type]||[])await fn({target,preventDefault(){}});};
  const click=async(dataset={},id='')=>emit('click',{closest:()=>({dataset,id,disabled:false})});
  const change=async(dataset={},value='',id='',checked=false)=>emit('change',{dataset,value,id,checked,closest(){return null;}});
  const input=async(id,value)=>emit('input',{id,value,dataset:{}});
  const seed=(kind,rows)=>{context.rows=rows;run('data['+JSON.stringify(kind)+']=rows;');};
  return {run,context,api:context.window.FlowManagement,el,els,requests,seed,click,change,input,emit,setHandler(fn){handler=fn;}};
}
const row=(id,changes={})=>({id,title:'需求'+id,owner:'小林',description:'描述',priority:'high',status:'draft',project_id:'p1',due_date:'2026-09-30',acceptance:'验收',created_at:'2026-09-11T00:00:00Z',updated_at:'2026-09-11T00:00:00Z',completed_at:null,...changes});
async function test(name,fn){await fn();console.log('PASS',name);count++;}
(async()=>{
  await test('Sidebar has one workbench, no extra management pages',()=>{assert(html.includes('项目工作台'));assert(!html.includes('data-nav="gantt"'));assert(!html.includes('data-nav="requirements"'));assert(!html.includes('data-nav="defects"'));assert.equal((html.match(/id="management-dialog"/g)||[]).length,1);});
  await test('Three scoped management tabs, gantt is not a top-level tab',()=>{const t=setup();assert.equal((t.api.nav().match(/data-management-route=/g)||[]).length,3);assert(!t.api.nav().includes('甘特图'));assert(t.api.nav().includes('计划管理'));});
  await test('Plan views include list, board and embedded gantt',()=>{const t=setup();assert.equal((t.run('taskViewToggle()').match(/data-mode=/g)||[]).length,3);t.run("mode='gantt';render();");assert(t.el('#content').innerHTML.includes('id="gantt-view"'));assert(t.el('#content').innerHTML.includes('列表'));assert(t.el('#content').innerHTML.includes('看板'));});
  await test('Gantt hash restores as a plan view, old links remain valid',()=>{const t=setup();t.run("location.hash='#tasks/gantt';hydrateRoute();");assert.equal(t.run('section'),'tasks');assert.equal(t.run('mode'),'gantt');t.run("location.hash='#project/p1/gantt';hydrateRoute();");assert.equal(t.run('projectId'),'p1');t.run("location.hash='#gantt';hydrateRoute();");assert.equal(t.run('section'),'tasks');});
  await test('Project stays selected when switching management tabs',async()=>{const t=setup();t.run("projectId='p1';");await t.click({managementRoute:'requirements'});assert.equal(t.run('section'),'requirements');assert.equal(t.run('projectId'),'p1');assert.equal(t.context.location.hash,'#project/p1/requirements');});
  await test('Overview stays overview; module stats are integrated cards',()=>{const t=setup();t.seed('requirements',[row('r1')]);t.run("section='overview';render();");assert(t.el('#management-nav').hidden);assert(t.el('#content').innerHTML.includes('需求跟进'));assert(t.el('#content').innerHTML.includes('未关闭缺陷'));});
  await test('Old backend shows explicit upgrade warning',()=>{const t=setup();t.run('delete data.requirements');assert(t.api.page('requirements').includes('本地服务需要升级'));});
  await test('Requirement and defect rows cannot execute HTML',()=>{const t=setup();t.seed('requirements',[row('r1',{title:'<img src=x onerror=1>'})]);const r=t.api.page('requirements');assert(r.includes('&lt;img'));assert(!r.includes('<img'));t.seed('defects',[row('d1',{status:'open',severity:'critical',title:'<script>bad</script>'})]);const d=t.api.page('defects');assert(d.includes('&lt;script&gt;'));assert(d.includes('致命'));});
  await test('Requirement search filters owner without rebuilding the form',async()=>{const t=setup();t.seed('requirements',[row('r1'),row('r2',{owner:'小周'})]);t.run("section='requirements';render();");await t.input('management-search','小周');assert(t.el('#management-results').innerHTML.includes('需求r2'));assert(!t.el('#management-results').innerHTML.includes('需求r1'));});
  await test('Requirements respect project scope and state filters',async()=>{const t=setup();t.seed('requirements',[row('r1'),row('r2',{project_id:'p2',status:'done'}),row('r3',{status:'done'})]);t.run("section='requirements';projectId='p1';");await t.change({managementFilter:'status'},'done');const result=t.el('#management-results').innerHTML;assert(result.includes('需求r3'));assert(!result.includes('需求r1'));assert(!result.includes('需求r2'));});
  await test('Defect severity filtering is separate from priority',async()=>{const t=setup();t.seed('defects',[row('d1',{status:'open',severity:'critical',priority:'low'}),row('d2',{status:'open',severity:'minor',priority:'urgent'})]);t.run("section='defects';");await t.change({managementFilter:'severity'},'critical');assert(t.el('#management-results').innerHTML.includes('需求d1'));assert(!t.el('#management-results').innerHTML.includes('需求d2'));});
  await test('Selection is cleared when filters change',async()=>{const t=setup();t.seed('requirements',[row('r1'),row('r2')]);t.run("section='requirements';");await t.change({managementSelect:'r1'},'','',true);assert(t.el('#management-results').innerHTML.includes('已选 1 项'));await t.change({managementFilter:'priority'},'high');assert(!t.el('#management-results').innerHTML.includes('已选 1 项'));});
  await test('Pagination bounds, empty search and clearing',async()=>{const t=setup();t.seed('requirements',Array.from({length:21},(_,i)=>row('r'+String(i).padStart(2,'0'))));t.run("section='requirements';");await t.click({managementPage:'99'});assert(t.el('#management-results').innerHTML.includes('3 / 3'));await t.input('management-search','not found');assert(t.el('#management-results').innerHTML.includes('没有匹配的需求'));await t.click({managementClear:'1'});assert(t.el('#content').innerHTML.includes('1 / 3'));});
  await test('Requirement modal has acceptance fields and project default',()=>{const t=setup();t.run("projectId='p1';");t.api.open('requirements');assert(t.el('#management-dialog').open);const fields=t.el('#management-fields').innerHTML;assert(fields.includes('name="acceptance"'));assert(fields.includes('value="p1" selected'));assert(!fields.includes('name="severity"'));});
  await test('Defect modal has reproducibility and severity fields',()=>{const t=setup();t.api.open('defects');for(const name of ['severity','environment','steps','expected','actual'])assert(t.el('#management-fields').innerHTML.includes('name="'+name+'"'));});
  await test('Save uses opening revision and duplicate submissions are locked',async()=>{const t=setup();t.api.open('requirements');let resolve;t.setHandler(()=>new Promise(r=>resolve=r));const form={id:'management-form',values:{kind:'requirements',id:'',title:'新需求',owner:'用户',description:'',project_id:'',priority:'medium',status:'draft',due_date:'',acceptance:'测试'}};const pending=t.emit('submit',form);await t.emit('submit',form);assert.equal(t.requests.length,1);assert.equal(t.requests[0].options.headers['If-Match'],'4');assert.equal(JSON.parse(t.requests[0].options.body).project_id,null);resolve({ok:true,status:200,json:async()=>t.run('data')});await pending;assert(!t.el('#management-dialog').open);});
  await test('Failed saves preserve the modal and show actionable errors',async()=>{const t=setup();t.api.open('defects');t.setHandler(async()=>({ok:false,status:400,json:async()=>({error:'严重程度无效'})}));await t.emit('submit',{id:'management-form',values:{kind:'defects',id:'',title:'错误',owner:'用户'}});assert(t.el('#management-dialog').open);assert(t.el('#management-error').textContent.includes('严重程度无效'));assert.equal(t.run('busy'),false);});
  await test('Inline status uses the right entity endpoint and preserves details',async()=>{const t=setup();t.seed('defects',[row('d1',{status:'open',severity:'major',steps:'步骤'})]);t.run("section='defects';");await t.change({managementStatus:'d1'},'verify');assert.equal(t.requests[0].url,'/api/defects/d1');const payload=JSON.parse(t.requests[0].options.body);assert.equal(payload.steps,'步骤');assert.equal(payload.status,'verify');});
  await test('Calendar math rejects invalid dates and includes same-day work',()=>{const t=setup(),o=t.api.ordinal;assert.equal(o('2026-02-30'),null);assert.equal(o(''),null);assert.equal(o('2026-9-1'),null);const g=t.api.geometry({start_date:'2026-09-11',due_date:'2026-09-11'},o('2026-09-11'),28,38);assert.equal(g.width,38);assert.equal(g.left,0);});
  await test('Gantt clips long tasks without unbounded DOM or negative width',()=>{const t=setup(),o=t.api.ordinal,g=t.api.geometry({start_date:'0001-01-01',due_date:'9999-12-31'},o('2026-09-11'),28,38);assert.equal(g.width,28*38);assert(g.clippedStart&&g.clippedEnd);assert.equal(t.api.geometry({start_date:'',due_date:'2026-09-11'},o('2026-09-11'),28,38).scheduled,false);assert.equal(t.api.geometry({start_date:'2026-09-12',due_date:'2026-09-11'},o('2026-09-11'),28,38).scheduled,false);});
  await test('Gantt handles leap days and tasks outside visible range',()=>{const t=setup(),o=t.api.ordinal;assert.equal(o('2024-03-01')-o('2024-02-28'),2);assert.equal(t.api.geometry({start_date:'2026-01-01',due_date:'2026-01-02'},o('2026-09-11'),28,38).outside,true);});
  await test('Unscheduled tasks remain discoverable; no fake dates',()=>{const t=setup();t.seed('tasks',[row('t1',{status:'todo',progress:0,start_date:'',due_date:''})]);const result=t.api.gantt(true);assert(result.includes('补充开始 / 截止日期'));assert(result.includes('1 项待补充日期'));assert(!result.includes('class="gantt-bar '));});
  await test('Gantt escapes titles and limits each page to forty rows',()=>{const t=setup();t.seed('tasks',Array.from({length:100},(_,i)=>row('t'+i,{status:'todo',progress:0,title:'<img>'+i,start_date:'2026-09-11'})));const result=t.api.gantt(true);assert.equal((result.match(/class="gantt-row"/g)||[]).length,40);assert(!result.includes('<img>'));assert(result.includes('&lt;img&gt;'));});
  await test('Filters are shared between list and gantt views',async()=>{const t=setup();t.seed('tasks',[row('t1',{status:'doing',start_date:'2026-09-11',progress:20,owner:'甲'}),row('t2',{status:'todo',start_date:'2026-09-11',progress:0,owner:'乙'})]);t.run("filters.query='甲';");await t.click({mode:'gantt'});assert(t.el('#content').innerHTML.includes('需求t1'));assert(!t.el('#content').innerHTML.includes('需求t2'));await t.input('gantt-search','乙');assert.equal(t.run('filters.query'),'乙');await t.click({mode:'list'});assert(t.el('#content').innerHTML.includes('需求t2'));assert(!t.el('#content').innerHTML.includes('需求t1'));});
  await test('All modules reuse the same heading and modal-only editing',()=>{const t=setup();for(const section of ['tasks','requirements','defects']){t.run('section='+JSON.stringify(section)+';render();');assert(t.el('#page-title').innerHTML.includes('在一个工作台'));assert(t.el('.heading-actions').hidden);assert(!t.el('#management-nav').hidden);}});
  console.log(count+' management frontend checks passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
